FROM zhayujie/chatgpt-on-wechat:debian

LABEL maintainer="foo@bar.com"
ARG TZ='Asia/Shanghai'

USER root



# replace entrypoint
ADD ./entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

USER noroot

ENTRYPOINT ["/entrypoint.sh"]
